##
#依赖: asciidoctor-bibtex, asciidoctor-diagram, graphviz, plantuml
##

baseurl: /
title: ybyte blog
languageCode: zh-cn
enableRobotsTXT: true
enableEmoji: true
theme: even

hasCJKLanguage: true      # has chinese/japanese/korean ? # 自动检测是否包含 中文\日文\韩文
paginate: 10              # Number of articles displayed on the homepage  # 首页每页显示的文章数
rssLimit: 20              # Limit Entry Count to Rss file # 限制 Rss 文章输出数量
disqusShortname: ybyte    # disqus_shortname
googleAnalytics:          # UA-XXXXXXXX-X
copyright:                # default: author.name ↓        # 默认为下面配置的author.name ↓
enableGitInfo: true

# Shortcode
#pygmentsUseClassic: true
#pygmentsCodeFences: true
#pygmentsUseClasses: true # Use CSS classes to format highlighted code
#pygmentsCodefencesGuessSyntax: true
#pygmentsOptions: "linenos=table"
#pygmentsStyle: monokai    # github,paraiso-light,monokai

# language support # en / zh-cn / other... translations present in i18n/

defaultContentLanguage: en           # Default language to use
languages:
  en:
    languageCode: en

author:                   # essential                     # 必需
  name: penglei

sitemap:                  # essential                     # 必需
  changefreq: weekly
  priority: 0.5
  filename: sitemap.xml

menu:
  main:                   # config your menu
  - name: Home
    weight: 10
    identifier: home
    url: /
  - name: Archives
    weight: 20
    identifier: archives
    url: /post/
  - name: Tags
    weight: 20
    identifier: tags
    url: /tags/
  - name: Categories
    weight: 30
    identifier: categories
    url: /categories/

params:
  version: 4.x           # Used to give a friendly message when you have an incompatible update
  debug: false             # If true, load `eruda.min.js`. See https://github.com/liriliri/eruda
  since: "2017"            # Site creation time          # 站点建立时间
  homeFullContent: false   # if false, show post summaries on home page. Othewise show full content.
  rssFullContent: true     # if false, Rss feed instead of the summary

  archivePaginate: 5 # paginate of archives, tags and categories   # 归档、标签、分类每页显示的文章数目，建议修改为一个较大的值
  gitRepo: https://github.com/penglei/penglei.github.io
  sourceGitBranch: source
  # site info (optional)                                  # 站点信息（可选，不需要的可以直接注释掉）
  logoTitle: "ybyte"        # default: the title value    # 默认值: 上面设置的title值
  keywords: ["linux", "kubernetes", "docker", "istio", "servicemesh", "sidecar"]
  description: "记录点滴"

  # The date format to use; for a list of valid formats, see https://gohugo.io/functions/format/
  dateFormatToUse: "2006-01-02"

  # 一些全局开关，你也可以在每一篇内容的 front matter 中针对单篇内容关闭或开启某些功能，在 archetypes/default.md 查看更多信息。
  # Some global options, you can also close or open something in front matter for a single post, see more information from `archetypes/default.md`.
  toc: true               # table of content
  photoswipe: true        # see https://github.com/dimsemenov/PhotoSwipe            # 是否启用PhotoSwipe（图片可点击）
  contentCopyright: '<a rel="license noopener" href="https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank">CC BY-NC-ND 4.0</a>'
  postMetaInFooter: true   # contain author, lastMod, markdown link, license           # 包含作者，上次修改时间，markdown链接，许可信息

  defaultCSS:
    - asciidoctor.css

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  customCSS:               # if ['custom.css'], load '/static/css/custom.css' file
    - highlightjs/github.css
    - custom.css
  customJS:                # if ['custom.js'], load '/static/js/custom.js' file
    - highlight.pack.js
    - init.js

  social:
    g-github: https://github.com/penglei

privacy:
  disqus:
    disable: false

